language: java

jdk:
  - openjdk11

branches:
  only:
  - master

cache:
  directories:
    - $HOME/.m2

sudo: false

install: true

script:
  - ./mvnw clean verify -Pneo4j-3.5

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - |
    curl -X "POST" "https://api.travis-ci.com/repo/michael-simons%2Fneo4j-spring-boot-integration-tests/requests" \
         -H "Authorization: token $SDN_BOOT_INTEGRATION_TESTS_TOKEN" \
         -H 'Travis-API-Version: 3' \
         -H 'Content-Type: application/json; charset=utf-8' \
         -d $'{
      "request": {
        "branch": "master"
      }
    }'

